import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { schedule } from "@/content/content";
import { GOOGLE_CALENDAR_EMBED_URL } from "@/lib/config";
import { buttonClasses } from "@/components/ui/button";
import { cn } from "@/lib/utils";

/**
 * ── HOW TO CONNECT DIANA'S REAL GOOGLE CALENDAR ────────────────────────────
 *
 * Diana maintains her schedule forever just by editing Google Calendar on
 * her phone. One-time setup for her team:
 *
 *  1. In Google Calendar (desktop), create TWO calendars:
 *       "In-Person — Move with Diana"  and  "Online — Move with Diana".
 *     Give each a distinct color (we suggest a blue-grey for In-Person and
 *     a warm brown for Online, to match the legend chips on the site).
 *  2. For EACH calendar: Settings → "Access permissions for events" →
 *     check "Make available to public" (See only free/busy is NOT enough —
 *     choose "See all event details" so class names show).
 *  3. Go to Settings → "Integrate calendar" is per-calendar, but to embed
 *     BOTH in one iframe use https://calendar.google.com/calendar/u/0/embedhelper
 *     ("Customize" button on any calendar's Integrate page):
 *       • Tick both calendars in the left sidebar.
 *       • View: WEEK. Untick "Print icon" and "Tabs" for a cleaner look.
 *       • Copy ONLY the URL inside src="..." of the generated iframe code.
 *  4. Paste that URL into GOOGLE_CALENDAR_EMBED_URL in src/lib/config.ts.
 *     (Optional: append "&mode=AGENDA" for list view — this component
 *     already switches to AGENDA automatically on small screens.)
 *  5. Rebuild/redeploy. Done — from now on, adding or moving a class in
 *     Google Calendar updates the site automatically.
 *
 * While GOOGLE_CALENDAR_EMBED_URL is an empty string, a designed sample
 * week renders instead — never a broken iframe.
 * ───────────────────────────────────────────────────────────────────────────
 */

/**
 * Slot-type marker: filled steel dot for in-person, umber ring for online —
 * distinguishable by shape as well as color (WCAG 1.4.1).
 */
function legendDot(type: "in-person" | "online") {
  return type === "in-person" ? "bg-steel" : "border-2 border-umber bg-transparent";
}

/** Text label for a slot type — reuses the legend labels from content.ts. */
function typeLabel(type: "in-person" | "online") {
  return schedule.legend.find((l) => l.type === type)?.label ?? type;
}

/**
 * Force the calendar's view mode. Google honors the FIRST mode= param, and
 * URLs generated by the embed helper usually already contain one — so replace
 * any existing mode rather than appending a duplicate that would be ignored.
 */
function withMode(url: string, mode: "WEEK" | "AGENDA") {
  try {
    const parsed = new URL(url);
    parsed.searchParams.set("mode", mode);
    return parsed.toString();
  } catch {
    // Not a parseable absolute URL — fall back to a plain append.
    const joiner = url.includes("?") ? "&" : "?";
    return `${url}${joiner}mode=${mode}`;
  }
}

/** Desktop gets the WEEK grid; phones get the AGENDA list (far more legible). */
function useIsDesktop() {
  const [isDesktop, setIsDesktop] = useState(
    () => typeof window !== "undefined" && window.matchMedia("(min-width: 768px)").matches,
  );
  useEffect(() => {
    const mq = window.matchMedia("(min-width: 768px)");
    const onChange = (e: MediaQueryListEvent) => setIsDesktop(e.matches);
    mq.addEventListener("change", onChange);
    return () => mq.removeEventListener("change", onChange);
  }, []);
  return isDesktop;
}

export default function ScheduleEmbed() {
  const hasCalendar = GOOGLE_CALENDAR_EMBED_URL.trim().length > 0;
  const isDesktop = useIsDesktop();

  return (
    <div>
      {/* Legend chips — colors match the two Google Calendars */}
      <ul className="mb-5 flex flex-wrap gap-3">
        {schedule.legend.map((item) => (
          <li
            key={item.label}
            className="inline-flex items-center gap-2 rounded-full border border-ink/10 bg-bone px-3.5 py-1.5 text-xs font-semibold"
          >
            <span className={cn("h-2 w-2 rounded-full", legendDot(item.type))} aria-hidden />
            {item.label}
          </li>
        ))}
      </ul>

      {hasCalendar ? (
        <div className="overflow-hidden rounded-photo border border-ink/10 bg-white shadow-sm">
          {/* One iframe, mode picked per viewport (avoids double-loading the
              calendar). Fixed height reserves space — no layout shift. */}
          <iframe
            src={withMode(GOOGLE_CALENDAR_EMBED_URL, isDesktop ? "WEEK" : "AGENDA")}
            title="Weekly class schedule"
            className={cn("w-full", isDesktop ? "h-[600px]" : "h-[480px]")}
            frameBorder="0"
            scrolling="no"
          />
        </div>
      ) : (
        <SampleWeek />
      )}
    </div>
  );
}

/** Designed static fallback: a clearly-labeled sample week. */
function SampleWeek() {
  return (
    <div className="rounded-photo border border-ink/10 bg-white/60 p-4 shadow-sm md:p-6">
      <p className="mb-4 inline-block rounded-full bg-plaster px-3.5 py-1.5 text-xs font-semibold text-ink/80">
        {schedule.fallback.note}
      </p>

      {/* Mobile: stacked day list. Desktop: 7-column week grid. */}
      <ul className="grid gap-2 md:grid-cols-7 md:gap-3">
        {schedule.fallback.days.map((day) => (
          <li key={day.day} className="rounded-lg bg-bone p-3">
            <p className="mb-2 text-xs font-semibold uppercase tracking-eyebrow text-umber">
              {day.day}
            </p>
            {day.slots.length === 0 ? (
              <p className="text-sm text-umber">{schedule.fallback.emptyDayLabel}</p>
            ) : (
              <ul className="space-y-2">
                {day.slots.map((slot) => (
                  <li key={`${day.day}-${slot.time}`} className="text-sm leading-snug">
                    <span className="flex items-center gap-1.5 font-semibold tabular-nums">
                      <span
                        className={cn("h-2 w-2 shrink-0 rounded-full", legendDot(slot.type))}
                        aria-hidden
                      />
                      {slot.time}
                    </span>
                    <span className="text-ink/80">{slot.name}</span>
                    {/* The colored dot alone would convey type by hue only —
                        spell it out for screen readers. */}
                    <span className="sr-only"> — {typeLabel(slot.type)}</span>
                  </li>
                ))}
              </ul>
            )}
          </li>
        ))}
      </ul>

      <div className="mt-6 text-center">
        <Link to="/contact" className={buttonClasses("ghost")}>
          {schedule.fallback.cta}
        </Link>
      </div>
    </div>
  );
}
